
# Define the base offers
$offers = @(
    @{ name = "Compensair"; link = "https://tp.media/r?marker=605475&trs=488170&p=4129&u=https%3A%2F%2Fcompensair.com&campaign_id=86"; sub = "claims"; keywords = @("flight delay compensation", "airline refund help", "cancelled flight claim", "missed connection compensation", "denied boarding rights", "eu261 compensation guide", "flight compensation germany", "flight compensation uk", "flight compensation spain", "flight compensation france") },
    @{ name = "Airalo eSIM"; link = "https://tp.media/r?marker=605475&trs=488170&p=8310&u=https%3A%2F%2Fairalo.com&campaign_id=541"; sub = "connectivity"; keywords = @("esim for international travel", "cheap travel data plan", "best esim for europe", "esim vs physical sim", "travel internet access", "digital sim card", "roaming data alternative", "esim for usa travel", "esim for asia travel", "global data pack") },
    @{ name = "Yesim"; link = "https://tp.media/r?marker=605475&trs=488170&p=5998&u=https%3A%2F%2Fyesim.tech&campaign_id=224"; sub = "connectivity"; keywords = @("pay as you go esim", "unlimited data travel sim", "virtual sim card app", "internet abroad", "international roaming app", "best travel sim card", "data plan for travelers", "global internet access", "esim for business travel", "cheap roaming changes") },
    @{ name = "DrimSim"; link = "https://tp.media/r?marker=605475&trs=488170&p=2762&u=https%3A%2F%2Fw1.drimsim.com&campaign_id=102"; sub = "connectivity"; keywords = @("universal sim card", "global roaming sim", "cheap international calls", "travel sim card europe", "sim card for sailors", "worldwide mobile internet", "no contract travel sim", "data sim for travel", "international sim card", "roaming free sim") },
    @{ name = "EKTA Insurance"; link = "https://tp.media/r?marker=605475&trs=488170&p=5869&u=https%3A%2F%2Fektatraveling.com&campaign_id=225"; sub = "insurance"; keywords = @("travel insurance for digital nomads", "covid travel insurance", "medical travel insurance", "luggage loss insurance", "cancel for any reason insurance", "adventure sports insurance", "visa travel insurance", "family travel insurance", "budget travel insurance", "annual travel insurance") },
    @{ name = "KiwiTaxi"; link = "https://tp.media/r?marker=605475&trs=488170&p=647&u=https%3A%2F%2Fkiwitaxi.com&campaign_id=1"; sub = "transfers"; keywords = @("airport transfer service", "private car service airport", "taxi transfer booking", "airport shuttle bus", "chauffeured car rental", "city to city transfer", "luxury airport transfer", "cheap airport taxi", "reliable airport pickup", "ski transfer service") },
    @{ name = "GetTransfer"; link = "https://tp.media/r?marker=605475&trs=488170&p=4439&u=https%3A%2F%2Fgettransfer.com&campaign_id=147"; sub = "transfers"; keywords = @("book private driver", "hourly car rental with driver", "airport meet and greet", "vip transfer service", "minivan rental with driver", "long distance taxi", "pet friendly transfer", "business travel transfer", "event transport service", "wedding car hire") },
    @{ name = "Intui Travel"; link = "https://tp.media/r?marker=605475&trs=488170&p=657&u=https%3A%2F%2Fintui.travel&campaign_id=22"; sub = "transfers"; keywords = @("hotel transfer shuttle", "airport to hotel bus", "shared airport transfer", "cheap shuttle service", "group travel transfer", "accessible airport transfer", "ski resort shuttle", "beach transfer service", "city center shuttle", "theme park transfer") },
    @{ name = "Welcome Pickups"; link = "https://tp.media/r?marker=605475&trs=488170&p=8919&u=https%3A%2F%2Fwelcomepickups.com&campaign_id=627"; sub = "transfers"; keywords = @("personalized airport pickup", "local driver guide", "sightseeing transfer", "welcome to city transfer", "safe airport pickup", "english speaking driver", "family friendly transfer", "airport taxi app", "private city tour", "custom transfer route") },
    @{ name = "Klook"; link = "https://tp.media/r?marker=605475&trs=488170&p=4110&u=https%3A%2F%2Fklook.com&campaign_id=137"; sub = "activities"; keywords = @("best things to do in asia", "discount attraction tickets", "japan rail pass", "universal studios tickets", "disneyland tickets", "best food tours", "cultural experiences", "adventure activities", "sim card klook", "airport train tickets") },
    @{ name = "Tiqets"; link = "https://tp.media/r?marker=605475&trs=488170&p=2074&u=https%3A%2F%2Ftiqets.com&campaign_id=89"; sub = "activities"; keywords = @("skip the line tickets", "museum tickets online", "last minute attraction tickets", "louvre museum tickets", "colosseum tickets", "sagrada familia tickets", "van gogh museum tickets", "rijksmuseum tickets", "eiffel tower tickets", "vatican museum tickets") },
    @{ name = "WeGoTrip"; link = "https://tp.media/r?marker=605475&trs=488170&p=4487&u=https%3A%2F%2Fwegotrip.com&campaign_id=150"; sub = "activities"; keywords = @("self guided audio tours", "walking tour app", "museum audio guide", "city exploration game", "historical walking tour", "architecture tour", "food tasting tour", "street art tour", "ghost tour", "nature walk guide") },
    @{ name = "TicketNetwork"; link = "https://tp.media/r?marker=605475&trs=488170&p=1948&u=https%3A%2F%2Fticketnetwork.com&campaign_id=72"; sub = "events"; keywords = @("concert tickets online", "sports event tickets", "broadway show tickets", "theater tickets", "nba tickets", "nfl tickets", "music festival tickets", "comedy show tickets", "las vegas show tickets", "sold out event tickets") },
    @{ name = "Aviasales"; link = "https://tp.media/r?marker=605475&trs=488170&p=4114&u=https%3A%2F%2Faviasales.com&campaign_id=100"; sub = "flights"; keywords = @("cheap flights scanner", "low cost airlines", "flight comparison site", "last minute flight deals", "multi city flights", "business class deals", "student flight discounts", "weekend getaway flights", "holiday flight deals", "domestic flight offers") },
    @{ name = "Radical Storage"; link = "https://tp.media/r?marker=605475&trs=488170&p=5867&u=https%3A%2F%2Fradicalstorage.com&campaign_id=209"; sub = "storage"; keywords = @("luggage storage near me", "bag storage nyc", "luggage lockers london", "bag drop paris", "suitcase storage rome", "left luggage station", "secure bag storage", "24/7 luggage storage", "long term luggage storage", "airbnb luggage storage") },
    @{ name = "SeaRadar"; link = "https://tp.media/r?marker=605475&trs=488170&p=5907&u=https%3A%2F%2Fsearadar.com&campaign_id=258"; sub = "rentals"; keywords = @("yacht charter booking", "sailboat rental", "catamaran charter", "boat holiday rental", "sailing vacation", "bareboat charter", "skippered yacht charter", "luxury yacht rental", "mediterranean sailing", "caribbean boat rental") },
    @{ name = "NordVPN"; link = "https://tp.media/click?shmarker=605475&promo_id=8986&source_type=link&type=click&campaign_id=631&trs=488170"; sub = "security"; keywords = @("best travel vpn", "secure public wifi", "access blocked websites", "vpn for streaming", "encrypted internet connection", "protect personal data", "anonymous browsing", "vpn for digital nomads", "safe online banking", "bypass censorship") },
    @{ name = "NordPass"; link = "https://tp.media/click?shmarker=605475&promo_id=9023&source_type=link&type=click&campaign_id=631&trs=488170"; sub = "security"; keywords = @("secure password manager", "password vault app", "generate strong passwords", "share passwords securely", "autofill passwords", "encrypted password storage", "password security check", "cross platform password manager", "business password manager", "family password manager") }
)

$sql = "DROP TABLE IF EXISTS offers;`n`nCREATE TABLE offers (`n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),`n    partner_name TEXT NOT NULL,`n    affiliate_link TEXT NOT NULL,`n    primary_keyword TEXT NOT NULL,`n    target_country TEXT NOT NULL,`n    subdirectory TEXT NOT NULL,`n    language_code TEXT NOT NULL DEFAULT 'en',`n    slug TEXT,`n    status TEXT NOT NULL DEFAULT 'pending'`n);`n`nINSERT INTO offers (partner_name, affiliate_link, primary_keyword, target_country, subdirectory, status, language_code) VALUES"

$values = @()

foreach ($offer in $offers) {
    foreach ($keyword in $offer.keywords) {
        $name = $offer.name.Replace("'", "''")
        $link = $offer.link
        $kw = $keyword.Replace("'", "''")
        $sub = $offer.sub
        $values += "`n('$name', '$link', '$kw', 'Global', '$sub', 'pending', 'en')"
    }
}

$sql += ($values -join ",") + ";"

$sql | Out-File -FilePath "mega_seed.sql" -Encoding utf8
Write-Host "mega_seed.sql generated successfully with $(($values.Count)) offers."
